"""empty message

Revision ID: 0c1b4230c4b9
Revises: 925bd4f16243
Create Date: 2024-10-25 15:21:21.458442

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0c1b4230c4b9"
down_revision: Union[str, None] = "925bd4f16243"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "beatpacks", sa.Column("created_at", sa.Date(), nullable=False)
    )
    op.add_column(
        "beatpacks", sa.Column("updated_at", sa.DateTime(), nullable=False)
    )
    op.add_column("beats", sa.Column("created_at", sa.Date(), nullable=False))
    op.add_column(
        "beats", sa.Column("updated_at", sa.DateTime(), nullable=False)
    )
    op.add_column(
        "playlists", sa.Column("created_at", sa.Date(), nullable=False)
    )
    op.add_column(
        "playlists", sa.Column("updated_at", sa.DateTime(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("playlists", "updated_at")
    op.drop_column("playlists", "created_at")
    op.drop_column("beats", "updated_at")
    op.drop_column("beats", "created_at")
    op.drop_column("beatpacks", "updated_at")
    op.drop_column("beatpacks", "created_at")
    # ### end Alembic commands ###
