"""empty message

Revision ID: 925bd4f16243
Revises: 
Create Date: 2024-10-25 13:50:26.072847

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "925bd4f16243"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "albums",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("picture_url", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("created_at", sa.Date(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "beatpacks",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "beats",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("picture_url", sa.String(), nullable=True),
        sa.Column("file_url", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "chat",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "licenses",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("created_at", sa.Date(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notifications",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "playlists",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("picture_url", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "soundkits",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("picture_url", sa.String(), nullable=True),
        sa.Column("file_url", sa.String(), nullable=False),
        sa.Column("created_at", sa.Date(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "squads",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("views", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("picture_url", sa.String(), nullable=True),
        sa.Column("created_at", sa.Date(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tags",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "tracks",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("picture_url", sa.String(), nullable=True),
        sa.Column("file_url", sa.String(), nullable=False),
        sa.Column("created_at", sa.Date(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("picture_url", sa.String(), nullable=True),
        sa.Column("access_level", sa.String(), nullable=False),
        sa.Column("telegram_id", sa.Integer(), nullable=True),
        sa.Column("premium_level", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_adult", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.Date(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "album_to_tag_association",
        sa.Column("album_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["album_id"],
            ["albums.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.PrimaryKeyConstraint("album_id", "tag_id"),
    )
    op.create_table(
        "album_to_track_association",
        sa.Column("album_id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["album_id"],
            ["albums.id"],
        ),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["tracks.id"],
        ),
        sa.PrimaryKeyConstraint("album_id", "track_id"),
    )
    op.create_table(
        "artist_profiles",
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("picture_url", sa.String(), nullable=False),
        sa.Column("created_at", sa.Date(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "beat_to_soundkits_association",
        sa.Column("soundkit_id", sa.Integer(), nullable=False),
        sa.Column("beat_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["beat_id"],
            ["beats.id"],
        ),
        sa.ForeignKeyConstraint(
            ["soundkit_id"],
            ["soundkits.id"],
        ),
        sa.PrimaryKeyConstraint("soundkit_id", "beat_id"),
    )
    op.create_table(
        "beatpack_to_beat_association_table",
        sa.Column("beat_id", sa.Integer(), nullable=True),
        sa.Column("beatpack_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["beat_id"],
            ["beats.id"],
        ),
        sa.ForeignKeyConstraint(
            ["beatpack_id"],
            ["beatpacks.id"],
        ),
    )
    op.create_table(
        "beatpack_to_tag_association",
        sa.Column("beatpack_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["beatpack_id"],
            ["beatpacks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.PrimaryKeyConstraint("beatpack_id", "tag_id"),
    )
    op.create_table(
        "comments",
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "follower_to_squads_association",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("squad_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["squad_id"],
            ["squads.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "squad_id"),
    )
    op.create_table(
        "messages",
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "playlists_to_beat_association",
        sa.Column("playlists_id", sa.Integer(), nullable=False),
        sa.Column("beat_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["beat_id"],
            ["beats.id"],
        ),
        sa.ForeignKeyConstraint(
            ["playlists_id"],
            ["playlists.id"],
        ),
        sa.PrimaryKeyConstraint("playlists_id", "beat_id"),
    )
    op.create_table(
        "playlists_to_tag_association",
        sa.Column("playlists_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["playlists_id"],
            ["playlists.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.PrimaryKeyConstraint("playlists_id", "tag_id"),
    )
    op.create_table(
        "playlists_to_track_association",
        sa.Column("playlists_id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["playlists_id"],
            ["playlists.id"],
        ),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["tracks.id"],
        ),
        sa.PrimaryKeyConstraint("playlists_id", "track_id"),
    )
    op.create_table(
        "producer_profiles",
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("picture_url", sa.String(), nullable=False),
        sa.Column("created_at", sa.Date(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tag_to_beat_association",
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("beat_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["beat_id"],
            ["beats.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.PrimaryKeyConstraint("tag_id", "beat_id"),
    )
    op.create_table(
        "tag_to_soundkits_association",
        sa.Column("soundkit_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["soundkit_id"],
            ["soundkits.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.PrimaryKeyConstraint("soundkit_id", "tag_id"),
    )
    op.create_table(
        "track_to_tag_association",
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["tracks.id"],
        ),
        sa.PrimaryKeyConstraint("track_id", "tag_id"),
    )
    op.create_table(
        "user_to_albums_association",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("album_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["album_id"],
            ["albums.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "album_id"),
    )
    op.create_table(
        "user_to_albums_likes",
        sa.Column("album_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["album_id"],
            ["albums.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("album_id", "user_id"),
    )
    op.create_table(
        "user_to_beatpacks_likes",
        sa.Column("beat_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("beatpacks_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["beat_id"],
            ["beats.id"],
        ),
        sa.ForeignKeyConstraint(
            ["beatpacks_id"],
            ["beatpacks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("beat_id", "user_id", "beatpacks_id"),
    )
    op.create_table(
        "user_to_beatpacks_views_association",
        sa.Column("beatpacks_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["beatpacks_id"],
            ["beatpacks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("beatpacks_id", "user_id"),
    )
    op.create_table(
        "user_to_beats_views_association",
        sa.Column("beat_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["beat_id"],
            ["beats.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("beat_id", "user_id"),
    )
    op.create_table(
        "user_to_chat_association",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["chat.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "chat_id"),
    )
    op.create_table(
        "user_to_licenses_association",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("license_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["license_id"],
            ["licenses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "license_id"),
    )
    op.create_table(
        "user_to_playlists_association",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("playlist_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["playlist_id"],
            ["playlists.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "playlist_id"),
    )
    op.create_table(
        "user_to_playlists_likes",
        sa.Column("playlist_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["playlist_id"],
            ["playlists.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("playlist_id", "user_id"),
    )
    op.create_table(
        "user_to_playlists_views_association",
        sa.Column("playlist_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["playlist_id"],
            ["playlists.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("playlist_id", "user_id"),
    )
    op.create_table(
        "user_to_soundkits_likes",
        sa.Column("soundkit_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["soundkit_id"],
            ["soundkits.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("soundkit_id", "user_id"),
    )
    op.create_table(
        "user_to_soundkits_views_association",
        sa.Column("soundkit_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["soundkit_id"],
            ["soundkits.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("soundkit_id", "user_id"),
    )
    op.create_table(
        "user_to_squads_views_association",
        sa.Column("squad_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["squad_id"],
            ["squads.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("squad_id", "user_id"),
    )
    op.create_table(
        "user_to_tag_association",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "tag_id"),
    )
    op.create_table(
        "user_to_tracks_likes",
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["tracks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("track_id", "user_id"),
    )
    op.create_table(
        "user_to_tracks_views_association",
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["tracks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("track_id", "user_id"),
    )
    op.create_table(
        "user_to_views_association",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("album_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["album_id"],
            ["albums.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "album_id"),
    )
    op.create_table(
        "album_to_artist_association",
        sa.Column("album_id", sa.Integer(), nullable=False),
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["album_id"],
            ["albums.id"],
        ),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artist_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("album_id", "artist_id"),
    )
    op.create_table(
        "artist_to_squad_association",
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.Column("squad_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artist_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["squad_id"],
            ["squads.id"],
        ),
        sa.PrimaryKeyConstraint("artist_id", "squad_id"),
    )
    op.create_table(
        "artist_to_tags_association",
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artist_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.PrimaryKeyConstraint("artist_id", "tag_id"),
    )
    op.create_table(
        "artist_to_track_association",
        sa.Column("artist_profile_id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["artist_profile_id"],
            ["artist_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["tracks.id"],
        ),
        sa.PrimaryKeyConstraint("artist_profile_id", "track_id"),
    )
    op.create_table(
        "message_to_chat_association",
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["chat.id"],
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
        ),
        sa.PrimaryKeyConstraint("message_id", "chat_id"),
    )
    op.create_table(
        "producer_to_beat_association",
        sa.Column("producer_id", sa.Integer(), nullable=False),
        sa.Column("beat_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["beat_id"],
            ["beats.id"],
        ),
        sa.ForeignKeyConstraint(
            ["producer_id"],
            ["producer_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("producer_id", "beat_id"),
    )
    op.create_table(
        "producer_to_beatpacks_association",
        sa.Column("producer_profile_id", sa.Integer(), nullable=True),
        sa.Column("beatpack_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["beatpack_id"],
            ["beatpacks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["producer_profile_id"],
            ["producer_profiles.id"],
        ),
    )
    op.create_table(
        "producer_to_soundkits_association",
        sa.Column("soundkit_id", sa.Integer(), nullable=False),
        sa.Column("producer_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["producer_id"],
            ["producer_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["soundkit_id"],
            ["soundkits.id"],
        ),
        sa.PrimaryKeyConstraint("soundkit_id", "producer_id"),
    )
    op.create_table(
        "producer_to_squad_association",
        sa.Column("producer_id", sa.Integer(), nullable=False),
        sa.Column("squad_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["producer_id"],
            ["producer_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["squad_id"],
            ["squads.id"],
        ),
        sa.PrimaryKeyConstraint("producer_id", "squad_id"),
    )
    op.create_table(
        "producer_to_tags_association",
        sa.Column("producer_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["producer_id"],
            ["producer_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.PrimaryKeyConstraint("producer_id", "tag_id"),
    )
    op.create_table(
        "track_to_producer_association",
        sa.Column("producer_id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["producer_id"],
            ["producer_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["tracks.id"],
        ),
        sa.PrimaryKeyConstraint("producer_id", "track_id"),
    )
    op.create_table(
        "user_to_artist_association",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artist_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "artist_id"),
    )
    op.create_table(
        "user_to_comments_association",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("comment_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["comment_id"],
            ["comments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "comment_id"),
    )
    op.create_table(
        "user_to_message_association",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "message_id"),
    )
    op.create_table(
        "user_to_producer_association",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("producer_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["producer_id"],
            ["producer_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "producer_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_to_producer_association")
    op.drop_table("user_to_message_association")
    op.drop_table("user_to_comments_association")
    op.drop_table("user_to_artist_association")
    op.drop_table("track_to_producer_association")
    op.drop_table("producer_to_tags_association")
    op.drop_table("producer_to_squad_association")
    op.drop_table("producer_to_soundkits_association")
    op.drop_table("producer_to_beatpacks_association")
    op.drop_table("producer_to_beat_association")
    op.drop_table("message_to_chat_association")
    op.drop_table("artist_to_track_association")
    op.drop_table("artist_to_tags_association")
    op.drop_table("artist_to_squad_association")
    op.drop_table("album_to_artist_association")
    op.drop_table("user_to_views_association")
    op.drop_table("user_to_tracks_views_association")
    op.drop_table("user_to_tracks_likes")
    op.drop_table("user_to_tag_association")
    op.drop_table("user_to_squads_views_association")
    op.drop_table("user_to_soundkits_views_association")
    op.drop_table("user_to_soundkits_likes")
    op.drop_table("user_to_playlists_views_association")
    op.drop_table("user_to_playlists_likes")
    op.drop_table("user_to_playlists_association")
    op.drop_table("user_to_licenses_association")
    op.drop_table("user_to_chat_association")
    op.drop_table("user_to_beats_views_association")
    op.drop_table("user_to_beatpacks_views_association")
    op.drop_table("user_to_beatpacks_likes")
    op.drop_table("user_to_albums_likes")
    op.drop_table("user_to_albums_association")
    op.drop_table("track_to_tag_association")
    op.drop_table("tag_to_soundkits_association")
    op.drop_table("tag_to_beat_association")
    op.drop_table("producer_profiles")
    op.drop_table("playlists_to_track_association")
    op.drop_table("playlists_to_tag_association")
    op.drop_table("playlists_to_beat_association")
    op.drop_table("messages")
    op.drop_table("follower_to_squads_association")
    op.drop_table("comments")
    op.drop_table("beatpack_to_tag_association")
    op.drop_table("beatpack_to_beat_association_table")
    op.drop_table("beat_to_soundkits_association")
    op.drop_table("artist_profiles")
    op.drop_table("album_to_track_association")
    op.drop_table("album_to_tag_association")
    op.drop_table("users")
    op.drop_table("tracks")
    op.drop_table("tags")
    op.drop_table("squads")
    op.drop_table("soundkits")
    op.drop_table("playlists")
    op.drop_table("notifications")
    op.drop_table("licenses")
    op.drop_table("chat")
    op.drop_table("beats")
    op.drop_table("beatpacks")
    op.drop_table("albums")
    # ### end Alembic commands ###
