"""empty message

Revision ID: c84dd7a6c3ba
Revises: 0c1b4230c4b9
Create Date: 2024-10-29 20:24:11.588690

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c84dd7a6c3ba"
down_revision: Union[str, None] = "0c1b4230c4b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("squads", "views")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "squads",
        sa.Column("views", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
