"""empty message

Revision ID: ca67afc70dcd
Revises:
Create Date: 2024-09-17 20:03:52.695171

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ca67afc70dcd"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_to_artist_association",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("artist_profile_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["artist_profile_id"],
            ["artist_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "artist_profile_id"),
    )
    op.create_table(
        "user_to_producer_association",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("producer_profile_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["producer_profile_id"],
            ["producer_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "producer_profile_id"),
    )
    op.create_table(
        "album_track_association",
        sa.Column("album_id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["album_id"],
            ["albums.id"],
        ),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["tracks.id"],
        ),
        sa.PrimaryKeyConstraint("album_id", "track_id"),
    )
    op.alter_column(
        "artist_profiles",
        "description",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "artist_profiles",
        "description",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.drop_table("album_track_association")
    op.drop_table("user_to_producer_association")
    op.drop_table("user_to_artist_association")
    # ### end Alembic commands ###
